### ISSUE TITLE
Some improvements

### ISSUE THREAD

**Issue by igarrido-adalab** [Adalab/modulo-2-evaluacion-intermedia-GitTher#1]
Really cool job @GitTher !!!

Here you have some tips to improve the exercise:

### JavaScript: basic

- [x] Don't use an element to resolve the counter, a good old constant will suffice ;) <https://github.com/Adalab/modulo-2-evaluacion-intermedia-GitTher/blob/01173f9684ce86400594d8a406d73fb7b5ea517a/js/main.js#L9-L11>

### JavaScript: advanced

- [x] Check if the `<select>` has the default option (with no value).
- [x] You are writing many times `"trackEl.innerHTML = 'something';"`, what about making a function that accepts a string as param and paints it into `'trackEl'`?

### Good practices

- [x] Try to improve your commits messages. "Add JS" is a bit poor. "Add random number logic" is more explanatory.

### Further challenges

Then you can improve the game as you please, here you have some ideas:

- Show an image with the user and computer selection
- Make the input work when selecting the option.
- Add a reset button that cleans the select, the counter and writes the initial feedback
- Whatever you want!

### Call to action

Let me know if you have any doubts ;)

Go for it!!

> Do not close this issue until your teacher asks you to

**Comment by igarridomorillas** [comment]
Perfect!
